#!/usr/bin/env python3

# encode with name
import os
import threading
from glob import glob


def decode_batch(bin_list):
    for filename in bin_list:
        file_path_out = os.path.splitext(filename)[0] + '.png'
        cmd = "python inference.py --decode -i %s -o %s -m_dir ./weights/ --block_width 2048 --block_height 1024 -m 0" % (
            filename, file_path_out)
        os.system(cmd)


if __name__ == '__main__':
    bins = glob('**/*.bin', recursive=True)
    os.chdir("./Util/AE")
    os.system('python setup.py build')
    os.system('python setup.py install')
    os.chdir("../..")
    bin_list_len = bins.__len__()
    bin_list_1 = bins[:bin_list_len // 2]
    bin_list_2 = bins[bin_list_len // 2:]
    threads = []
    t1 = threading.Thread(target=decode_batch, args=(bin_list_1,))
    threads.append(t1)
    t2 = threading.Thread(target=decode_batch, args=(bin_list_2,))
    threads.append(t2)
    for t in threads:
        t.start()
    for t in threads:
        t.join()